In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv


In [2]:
df = pd.read_csv('/kaggle/input/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [3]:
df.shape

(10000, 14)

In [4]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [9]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [10]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [12]:
df.drop(columns=["RowNumber","CustomerId","Surname"], inplace=True)

In [13]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [16]:
df.shape

(10000, 11)

In [17]:
#One Hot Encode Geography and Gender column

df = pd.get_dummies(df, columns=['Geography','Gender'], drop_first=True)
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1              False   
1                  1        112542.58       0              False   
2                  0        113931.57       1              False   
3                  0         93826.63       0              False   
4                  1         79084.10       0              False   
...              ...              ...     ...                ...   
9995               0         96270.64       0              False   
9996               1        101699.77       0              False   
9997               1         42085.58       1              False   
9998               0         92888.52       1               True   
9999               0         38190.78       0              False   

      Geography_Spain  Gender_Male  
0               False        False  
1                True        False  
2               False        False  
3               False        False  
4                True        False  
...               ...          ...  
9995            False         True  
9996            False         True  
9997            False        False  
9998            False         True  
9999            False        False  

[10000 rows x 12 columns]

In [19]:
X = df.drop(columns = ['Exited'])
y = df['Exited']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [20]:
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0                  1        101348.88              False            False   
1                  1        112542.58              False             True   
2                  0        113931.57              False            False   
3                  0         93826.63              False            False   
4                  1         79084.10              False             True   
...              ...              ...                ...              ...   
9995               0         96270.64              False            False   
9996               1        101699.77              False            False   
9997               1         42085.58              False            False   
9998               0         92888.52               True            False   
9999               0         38190.78              False            False   

      Gender_Male  
0           False  
1           False  
2           False  
3           False  
4           False  
...           ...  
9995         True  
9996         True  
9997        False  
9998         True  
9999        False  

[10000 rows x 11 columns]

In [21]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [22]:
X_train.shape

(8000, 11)

In [23]:
#For scaling between -1 to 1
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [24]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)

In [25]:
X_train_scaled

array([[ 0.35649971, -0.6557859 ,  0.34567966, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [-0.20389777,  0.29493847, -0.3483691 , ...,  1.72572313,
        -0.57638802,  0.91324755],
       [-0.96147213, -1.41636539, -0.69539349, ..., -0.57946723,
         1.73494238,  0.91324755],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ..., -0.57946723,
        -0.57638802, -1.09499335],
       [ 0.15932282,  0.3900109 ,  1.03972843, ..., -0.57946723,
        -0.57638802,  0.91324755],
       [ 0.47065475,  1.15059039, -1.38944225, ...,  1.72572313,
        -0.57638802,  0.91324755]])

In [26]:
X_test_scaled

array([[-5.12501721e-01, -6.77299309e-01, -6.98445493e-01, ...,
         1.73668197e+00, -5.63491843e-01,  9.09111664e-01],
       [-2.36046598e-01,  3.84298354e-01, -1.38035469e+00, ...,
        -5.75810666e-01, -5.63491843e-01,  9.09111664e-01],
       [-4.61306328e-01,  4.80807232e-01, -3.57490896e-01, ...,
        -5.75810666e-01,  1.77464858e+00, -1.09997489e+00],
       ...,
       [ 8.59534812e-01,  7.70333868e-01,  6.65372897e-01, ...,
        -5.75810666e-01, -5.63491843e-01, -1.09997489e+00],
       [ 4.70449825e-01, -9.66825944e-01, -3.57490896e-01, ...,
        -5.75810666e-01, -5.63491843e-01,  9.09111664e-01],
       [-1.84851205e-01, -1.73715981e-03, -1.38035469e+00, ...,
         1.73668197e+00, -5.63491843e-01,  9.09111664e-01]])

In [28]:
import tensorflow
import tensorflow.keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [29]:
model = Sequential()

In [30]:
model.add(Dense(11, activation='relu', input_dim=11))
model.add(Dense(11, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
2026-02-15 02:59:24.578283: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [31]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [33]:
model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])
history = model.fit(X_train_scaled, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.7103 - loss: 0.6064 - val_accuracy: 0.8106 - val_loss: 0.4822
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8065 - loss: 0.4865 - val_accuracy: 0.8150 - val_loss: 0.4456
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8050 - loss: 0.4582 - val_accuracy: 0.8181 - val_loss: 0.4311
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8138 - loss: 0.4343 - val_accuracy: 0.8219 - val_loss: 0.4244
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8118 - loss: 0.4309 - val_accuracy: 0.8225 - val_loss: 0.4176
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8188 - loss: 0.4175 - val_accuracy: 0.8294 - val_loss: 0.4095
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8261 - loss: 0.4057 - val_accuracy: 0.8400 - val_loss: 0.3971
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8388 - loss: 0.3926 - val_accu

In [34]:
history.history

{'accuracy': [0.764843761920929,
  0.8028125166893005,
  0.8087499737739563,
  0.811718761920929,
  0.8149999976158142,
  0.821093738079071,
  0.831250011920929,
  0.8439062237739563,
  0.8496875166893005,
  0.8515625,
  0.8545312285423279,
  0.85546875,
  0.8592187762260437,
  0.8598437309265137,
  0.8587499856948853,
  0.8615624904632568,
  0.8620312213897705,
  0.8596875071525574,
  0.8607812523841858,
  0.8606250286102295,
  0.8600000143051147,
  0.8614062666893005,
  0.8607812523841858,
  0.8618749976158142,
  0.8623437285423279,
  0.8643749952316284,
  0.8626562356948853,
  0.8620312213897705,
  0.8631250262260437,
  0.86328125,
  0.862500011920929,
  0.8642187714576721,
  0.8610937595367432,
  0.8629687428474426,
  0.8628125190734863,
  0.8618749976158142,
  0.86328125,
  0.8634374737739563,
  0.8629687428474426,
  0.8629687428474426,
  0.8628125190734863,
  0.8629687428474426,
  0.862500011920929,
  0.8651562333106995,
  0.8623437285423279,
  0.86328125,
  0.8631250262260437,
 

In [35]:
model.layers[0].get_weights()

[array([[-7.14266673e-02,  2.74061114e-01,  1.04007594e-01,
         -9.74952877e-02, -2.54287869e-01,  1.96484849e-01,
          5.15592583e-02,  3.76638293e-01, -2.31620781e-02,
          6.55339146e-03, -3.76978144e-03],
        [ 8.53119642e-02,  3.89636487e-01,  2.19265252e-01,
          1.06241691e+00, -1.59624845e-01, -6.73332810e-02,
          4.66709584e-01, -1.26449257e-01, -9.78437126e-01,
         -5.88642657e-01,  9.29473519e-01],
        [-1.83387566e-02,  4.52048153e-01,  8.48248526e-02,
         -9.66579467e-02, -3.19406658e-01,  7.30382055e-02,
         -5.73544949e-02, -1.92290302e-02,  7.16591254e-02,
         -4.42704000e-02, -1.16117932e-01],
        [ 5.95568717e-02, -8.06175172e-03,  3.05446014e-02,
         -2.53078580e-01,  2.35200867e-01, -1.16241539e+00,
         -2.08243839e-02, -2.98101097e-01,  7.23381460e-01,
         -2.99468786e-01, -2.19538465e-01],
        [ 1.07115889e+00, -1.69101488e-02, -9.82439220e-01,
         -6.88703895e-01,  8.21278989e-03, -

In [37]:
model.layers[1].get_weights()

[array([[-1.58270504e-02, -7.36542165e-01,  1.95311934e-01,
          5.13518870e-01,  4.35834408e-01,  6.57993317e-01,
          8.75262246e-02,  3.14230531e-01, -2.66218424e-01,
         -2.18165457e-01,  4.81876850e-01],
        [ 8.19229424e-01,  4.08276200e-01,  1.45526573e-01,
          6.00837283e-02, -5.99105023e-02, -3.91767740e-01,
          2.54401594e-01,  3.45212728e-01,  4.54499692e-01,
         -2.40256250e-01, -3.40728201e-02],
        [ 3.30601543e-01,  6.27963006e-01,  3.64591926e-01,
          3.50606441e-01, -2.25083679e-01,  2.02637613e-01,
         -1.69244766e-01,  3.09715986e-01,  2.21222803e-01,
          6.03908360e-01, -3.75779450e-01],
        [-7.03268170e-01,  5.89051805e-02, -6.07258379e-01,
         -4.66781110e-01, -4.93616194e-01, -6.03919446e-01,
         -2.07386672e-01, -2.50247002e-01, -1.54343471e-01,
          3.38336200e-01, -3.65838856e-01],
        [-7.72154450e-01,  1.67635709e-01,  9.29879323e-02,
          1.50812879e-01,  2.16337606e-01, -

In [38]:
model.layers[2].get_weights()

[array([[ 0.98030573],
        [ 0.63345736],
        [-0.51692003],
        [ 0.7931448 ],
        [-0.91947556],
        [ 1.1346545 ],
        [-0.6987747 ],
        [-0.27967513],
        [-0.8850542 ],
        [ 0.60330373],
        [ 1.328775  ]], dtype=float32),
 array([-0.1078895], dtype=float32)]

In [39]:
y_log = model.predict(X_test_scaled)
print(y_log)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[0.02950993]
 [0.01852   ]
 [0.1225142 ]
 ...
 [0.7470075 ]
 [0.05754424]
 [0.31944638]]


In [40]:
y_pred = np.where(y_log>0.5,1,0)
print(y_pred)

[[0]
 [0]
 [0]
 ...
 [1]
 [0]
 [0]]
